name: com_igkdev_new_app
description: "WillOnHair - application - v4"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0


dependencies:
  convert: ^3.1.2
  dio: ^5.8.0+1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_local_notifications: ^19.2.1
  flutter_localizations: 
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  intl: ^0.20.2
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  orm: ^5.3.3
  test_api: ^0.7.4
  vector_math: ^2.1.4

  csc_picker: ^0.2.7
  package_info_plus:
  flutter_rating_bar: ^4.0.1
  #Date Picker
  flutter_rounded_date_picker: ^3.0.2
  flutter_localization: ^0.1.10
  #animations
  animations: ^2.0.3
  cupertino_stepper: ^0.2.1
  flutter_switch: ^0.3.2
  animated_splash_screen: ^1.3.0
  #spinKit
  flutter_spinkit: ^5.1.0
  #qr Code
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.2.1
  # GET
  # DIO

  # FONT
  font_awesome_flutter: ^10.4.0
  #IMAGES, SLIDERS, LAYOUTS
  flutter_cache_manager:
  cached_network_image: 3.2.2
  carousel_slider: 4.1.1
  flutter_svg: 1.1.5
  flutter_staggered_grid_view: 0.6.2
  image_picker: 0.8.6
  cupertino_icons: any
  shimmer: 2.0.0
  intl_phone_field: 3.1.0
  # WEB
  webview_flutter: 3.0.4 
  url_launcher: 6.1.6
  # DROPDDOWN SEARCH
  dropdown_search: ^5.0.6
  # FIREBASE
  # GOOGLE MAPS

  
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  data_table_2: ^2.4.2
  webview_flutter_plus: ^0.3.0+2
  change_app_package_name: ^1.1.0
  path_provider: ^2.0.15
  app_settings: ^4.2.0
  lottie: ^2.3.2
  pie_chart: ^5.3.2
  cloud_firestore: ^5.6.8
  dio_cache_interceptor: ^4.0.3
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
